In [14]:
import pandas as pd

In [17]:
!pip install xlrd # file is an older .xls format

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

In [20]:
df_2017 = pd.read_excel("multi-year-station-entry-and-exit-figures.xls", sheet_name="2017 Entry & Exit")
df_2017

,COUNTS - 2017 - annual entries & exits,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,"(C) Copyright, London Underground Limited, 2018",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,[ Weights,253,52,59,253,52,59,]
3,Counts by station,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Annual
4,,NaN,NaN,NaN,Entry,Entry,Entry,Exit,Exit,Exit,Entry + Exit
...,...,...,...,...,...,...,...,...,...,...,...
271,599,Wood Lane,Hammersmith and Fulham,,6242,4516,2267,6631,4294,2494,3.995888
272,769,Woodford,Redbridge,,9442,6937,4140,9537,6301,4142,5.978701
273,771,Woodside Park,Barnet,,5311,2997,2246,6089,3760,2967,3.543131
274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Total,NaN,NaN,4693300,3256834,2260533,4594502,3159447,2189423,2946.007922

In [22]:
#pre-inspecting file to know valid header
df_raw = pd.read_excel("multi-year-station-entry-and-exit-figures.xls", sheet_name="2017 Entry & Exit", header=None)
df_raw.head(10)

,0,1,2,3,4,5,6,7,8,9,10
0,COUNTS - 2017 - annual entries & exits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"(C) Copyright, London Underground Limited, 2018",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,[ Weights,253,52,59,253,52,59,]
4,Counts by station,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Annual
5,,NaN,NaN,NaN,Entry,Entry,Entry,Exit,Exit,Exit,Entry + Exit
6,nlc,Station,Borough,Note,Weekday,Saturday,Sunday,Weekday,Saturday,Sunday,million
7,500,Acton Town,Ealing,,9531,6716,4744,9382,6617,4785,6.040516
8,502,Aldgate,City of London,,15080,4397,3261,16023,5909,4230,8.84694
9,503,Aldgate East,Tower Hamlets,,22327,16166,13323,21071,13893,11347,13.998292

In [21]:
#Skip the junk rows at the top
df_2017 = pd.read_excel(
    "multi-year-station-entry-and-exit-figures.xls",
    sheet_name="2017 Entry & Exit",
    skiprows=6
)
df_2017.head()

,nlc,Station,Borough,Note,Weekday,Saturday,Sunday,Weekday.1,Saturday.1,Sunday.1,million
0,500.0,Acton Town,Ealing,,9531.0,6716.0,4744.0,9382.0,6617.0,4785.0,6.040516
1,502.0,Aldgate,City of London,,15080.0,4397.0,3261.0,16023.0,5909.0,4230.0,8.846940
2,503.0,Aldgate East,Tower Hamlets,,22327.0,16166.0,13323.0,21071.0,13893.0,11347.0,13.998292
3,505.0,Alperton,Brent,,4495.0,3279.0,2345.0,5081.0,3392.0,2445.0,3.052230
4,506.0,Amersham,Chiltern,,3848.0,1876.0,1232.0,4025.0,1797.0,1121.0,2.321692

In [23]:
df_2017.columns

Index(['nlc', 'Station', 'Borough', 'Note', 'Weekday', 'Saturday', 'Sunday',
       'Weekday.1', 'Saturday.1', 'Sunday.1', 'million'],
      dtype='object')

In [24]:
#Rename columns to be clear and unambiguous
df_2017.columns = ["nlc", "station", "borough", "note",
                    "entry_weekday", "entry_saturday", "entry_sunday",
                    "exit_weekday", "exit_saturday", "exit_sunday",
                    "annual_entry_exit_million"]
df_2017.head()

,nlc,station,borough,note,entry_weekday,entry_saturday,entry_sunday,exit_weekday,exit_saturday,exit_sunday,annual_entry_exit_million
0,500.0,Acton Town,Ealing,,9531.0,6716.0,4744.0,9382.0,6617.0,4785.0,6.040516
1,502.0,Aldgate,City of London,,15080.0,4397.0,3261.0,16023.0,5909.0,4230.0,8.846940
2,503.0,Aldgate East,Tower Hamlets,,22327.0,16166.0,13323.0,21071.0,13893.0,11347.0,13.998292
3,505.0,Alperton,Brent,,4495.0,3279.0,2345.0,5081.0,3392.0,2445.0,3.052230
4,506.0,Amersham,Chiltern,,3848.0,1876.0,1232.0,4025.0,1797.0,1121.0,2.321692

In [25]:
#Check for junk rows and data types
df_2017.info()
#visible here: 269 or 270 total, but nlc only has 268 non-null

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   nlc                        268 non-null    float64
 1   station                    269 non-null    object
 2   borough                    268 non-null    object
 3   note                       259 non-null    object
 4   entry_weekday              269 non-null    float64
 5   entry_saturday             269 non-null    float64
 6   entry_sunday               269 non-null    float64
 7   exit_weekday               269 non-null    float64
 8   exit_saturday              269 non-null    float64
 9   exit_sunday                269 non-null    float64
 10  annual_entry_exit_million  269 non-null    float64
dtypes: float64(8), object(3)
memory usage: 23.3+ KB

In [27]:
#Look at the bottom of the table to find the junk rows
df_2017.tail(10)

,nlc,station,borough,note,entry_weekday,entry_saturday,entry_sunday,exit_weekday,exit_saturday,exit_sunday,annual_entry_exit_million
260,765.0,Willesden Green,Brent,,13820.0,10754.0,8161.0,13073.0,9494.0,7811.0,8.799173
261,766.0,Willesden Junction,Brent,A,7566.0,5164.0,2908.0,7514.0,4743.0,3028.0,4.680628
262,767.0,Wimbledon,Merton,A,18188.0,15969.0,10013.0,20149.0,16795.0,10509.0,12.613787
263,768.0,Wimbledon Park,Merton,,3583.0,2648.0,1605.0,3301.0,2235.0,1600.0,2.184663
264,770.0,Wood Green,Haringey,,20042.0,15815.0,11793.0,18949.0,16020.0,11415.0,12.889415
265,599.0,Wood Lane,Hammersmith and Fulham,,6242.0,4516.0,2267.0,6631.0,4294.0,2494.0,3.995888
266,769.0,Woodford,Redbridge,,9442.0,6937.0,4140.0,9537.0,6301.0,4142.0,5.978701
267,771.0,Woodside Park,Barnet,,5311.0,2997.0,2246.0,6089.0,3760.0,2967.0,3.543131
268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,Total,NaN,NaN,4693300.0,3256834.0,2260533.0,4594502.0,3159447.0,2189423.0,2946.007922

In [28]:
#Remove rows where nlc is missing
df_2017 = df_2017[df_2017["nlc"].notna()]
df_2017.tail()

,nlc,station,borough,note,entry_weekday,entry_saturday,entry_sunday,exit_weekday,exit_saturday,exit_sunday,annual_entry_exit_million
263,768.0,Wimbledon Park,Merton,,3583.0,2648.0,1605.0,3301.0,2235.0,1600.0,2.184663
264,770.0,Wood Green,Haringey,,20042.0,15815.0,11793.0,18949.0,16020.0,11415.0,12.889415
265,599.0,Wood Lane,Hammersmith and Fulham,,6242.0,4516.0,2267.0,6631.0,4294.0,2494.0,3.995888
266,769.0,Woodford,Redbridge,,9442.0,6937.0,4140.0,9537.0,6301.0,4142.0,5.978701
267,771.0,Woodside Park,Barnet,,5311.0,2997.0,2246.0,6089.0,3760.0,2967.0,3.543131

In [29]:
df_2017.shape

(268, 11)

In [30]:
#Add a year column
df_2017["year"] = 2017
df_2017.head()

,nlc,station,borough,note,entry_weekday,entry_saturday,entry_sunday,exit_weekday,exit_saturday,exit_sunday,annual_entry_exit_million,year
0,500.0,Acton Town,Ealing,,9531.0,6716.0,4744.0,9382.0,6617.0,4785.0,6.040516,2017
1,502.0,Aldgate,City of London,,15080.0,4397.0,3261.0,16023.0,5909.0,4230.0,8.846940,2017
2,503.0,Aldgate East,Tower Hamlets,,22327.0,16166.0,13323.0,21071.0,13893.0,11347.0,13.998292,2017
3,505.0,Alperton,Brent,,4495.0,3279.0,2345.0,5081.0,3392.0,2445.0,3.052230,2017
4,506.0,Amersham,Chiltern,,3848.0,1876.0,1232.0,4025.0,1797.0,1121.0,2.321692,2017

In [32]:
#automate the same 8 steps for all 6 years at once
years = [2011, 2012, 2013, 2014, 2015, 2016, 2017]
all_years = []

for year in years:
    sheet = f"{year} Entry & Exit"
    df_year = pd.read_excel("multi-year-station-entry-and-exit-figures.xls", sheet_name=sheet, skiprows=6)

    if df_year.shape[1] == 11:
        df_year.columns = ["nlc", "station", "borough", "note",
                            "entry_weekday", "entry_saturday", "entry_sunday",
                            "exit_weekday", "exit_saturday", "exit_sunday",
                            "annual_entry_exit_million"]
    else:
        df_year.columns = ["nlc", "station", "note",
                            "entry_weekday", "entry_saturday", "entry_sunday",
                            "exit_weekday", "exit_saturday", "exit_sunday",
                            "annual_entry_exit_million"]
        df_year["borough"] = None

    df_year = df_year[df_year["nlc"].notna()]
    df_year["year"] = year
    all_years.append(df_year)

df_footfall = pd.concat(all_years, ignore_index=True)
df_footfall.shape

(1881, 12)

In [33]:
#Sanity-check the combined table
df_footfall["year"].value_counts().sort_index()

year
2011    269
2012    269
2013    269
2014    269
2015    268
2016    269
2017    268
Name: count, dtype: int64

In [34]:
df_footfall[df_footfall["year"] == 2011]["borough"].unique()

array([None], dtype=object)

In [35]:
#Convert the numeric columns properly
count_cols = ["entry_weekday", "entry_saturday", "entry_sunday",
              "exit_weekday", "exit_saturday", "exit_sunday",
              "annual_entry_exit_million"]

for col in count_cols:
    df_footfall[col] = pd.to_numeric(df_footfall[col], errors="coerce")

df_footfall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1881 entries, 0 to 1880
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   nlc                        1881 non-null   object
 1   station                    1876 non-null   object
 2   note                       1854 non-null   object
 3   entry_weekday              1876 non-null   float64
 4   entry_saturday             1876 non-null   float64
 5   entry_sunday               1876 non-null   float64
 6   exit_weekday               1876 non-null   float64
 7   exit_saturday              1876 non-null   float64
 8   exit_sunday                1876 non-null   float64
 9   annual_entry_exit_million  1876 non-null   float64
 10  borough                    1072 non-null   object
 11  year                       1881 non-null   int64
dtypes: float64(7), int64(1), object(4)
memory usage: 176.5+ KB

In [36]:
#Find those 5 problem rows
df_footfall[df_footfall["station"].isna()]

,nlc,station,note,entry_weekday,entry_saturday,entry_sunday,exit_weekday,exit_saturday,exit_sunday,annual_entry_exit_million,borough,year
268,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,2011
537,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,2012
806,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,2013
1075,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
1612,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016

In [37]:
#Add a second safety filter
df_footfall = df_footfall[df_footfall["station"].notna()]
df_footfall.shape
#it should now be 1881 - 5 = 1876 rows.

(1876, 12)

In [38]:
df_footfall.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1876 entries, 0 to 1880
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   nlc                        1876 non-null   object
 1   station                    1876 non-null   object
 2   note                       1854 non-null   object
 3   entry_weekday              1876 non-null   float64
 4   entry_saturday             1876 non-null   float64
 5   entry_sunday               1876 non-null   float64
 6   exit_weekday               1876 non-null   float64
 7   exit_saturday              1876 non-null   float64
 8   exit_sunday                1876 non-null   float64
 9   annual_entry_exit_million  1876 non-null   float64
 10  borough                    1072 non-null   object
 11  year                       1876 non-null   int64
dtypes: float64(7), int64(1), object(4)
memory usage: 190.5+ KB

In [39]:
#helpful derived columns
df_footfall["total_weekday"] = df_footfall["entry_weekday"] + df_footfall["exit_weekday"]
df_footfall["total_weekend"] = (df_footfall["entry_saturday"] + df_footfall["exit_saturday"] +
                                  df_footfall["entry_sunday"] + df_footfall["exit_sunday"])
df_footfall.head()

,nlc,station,note,entry_weekday,entry_saturday,entry_sunday,exit_weekday,exit_saturday,exit_sunday,annual_entry_exit_million,borough,year,total_weekday,total_weekend
0,500,Acton Town,,8702.0,6326.0,4216.0,8392.0,5976.0,4223.0,5.462387,None,2011,17094.0,20741.0
1,502,Aldgate,,11319.0,2358.0,2251.0,10919.0,3676.0,2758.0,6.235513,None,2011,22238.0,11043.0
2,503,Aldgate East,,15045.0,8983.0,8051.0,13957.0,8177.0,7672.0,9.157483,None,2011,29002.0,32883.0
3,505,Alperton,,4478.0,3357.0,2373.0,4665.0,3384.0,2399.0,2.945259,None,2011,9143.0,11513.0
4,506,Amersham,,3461.0,1496.0,975.0,3775.0,1582.0,869.0,2.099560,None,2011,7236.0,4922.0

In [40]:
#Export the clean file
df_footfall.to_csv("clean_station_footfall.csv", index=False)